---
title: Taxonomy Bar Plot of the Hingut
---


```{r libraries, include=FALSE}

library(tidyverse)
library(phyloseq)

# Load object
ps = readRDS('../datasets/ps_filtered.rds')

#Making a phylum-level plot.
ps_phylum = tax_glom(ps,'Phylum')
```
Creating a basic version of the bar plot.

```{r basic}
# Converting to relative abundance, then melt
relab = ps_phylum %>% 
  microbiome::transform('compositional') %>% 
  psmelt()


#Creating swim performance groups

relab <- relab %>%
  mutate(
    swim_group = case_when(
      swim_performance %in% c("flow refuging", "burrowing") ~ "slow",
      swim_performance == "generalist" ~ "moderate",
      swim_performance %in% c("cruiser sprinter", "accelerator", "manoeuvrer") ~ "fast",
      TRUE ~ NA_character_
    )
  )

# Plotting it out
plot_basic = relab %>% 
  ggplot(aes(Sample, Abundance, fill = Phylum)) +
  geom_col(position = 'stack')

plot_basic
```

```{r with formatting}
plot_formatted = relab %>% 
  mutate(swim_group = str_to_title(swim_group)) %>%
  
  ggplot(aes(Sample, Abundance, fill = Phylum)) +
  geom_col(position = 'stack') +
  
  facet_wrap(~swim_group, ncol = 3, scales = 'free') +
  
  theme_classic(base_size = 18) +
#Stopping the sample names from overlapping
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
# Remove the x axis label 
  xlab(NULL)

plot_formatted
```

```{r abundance filtered}

#averaging abundances of each phylum

sum_of_each_phylum = taxa_sums(ps_phylum)
avg_of_each_phylum = sum_of_each_phylum / sum(sum_of_each_phylum)

# Finding which ones are <1%

below_1 = avg_of_each_phylum[avg_of_each_phylum < 0.01]
to_change = names(below_1)
to_change

# Changing the phylum name of these ones to '<1%'

relab_modified = relab
unique(relab_modified$Phylum)
relab_modified$Phylum[relab_modified$OTU %in% to_change] = '<1%'
unique(relab_modified$Phylum)


#Plotting it again

plot_abfilt = relab_modified %>% 
  mutate(swim_group = str_to_title(swim_group)) %>%
  
  ggplot(aes(Sample, Abundance, fill = Phylum)) +
  geom_col(position = 'stack') +
  
  facet_wrap(~swim_group, ncol = 3, scales = 'free') +
  
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
  xlab(NULL)

plot_abfilt
```


```{r averaged plot}
#Averaging abundance by group

averaged = relab_modified %>% 
  group_by(OTU, Phylum, swim_group) %>% 
  summarize(Abundance = mean(Abundance), .groups = "drop")



plot_avg = averaged %>% 
  filter(!is.na(swim_group)) %>% 
  mutate(swim_group = str_to_title(swim_group)) %>%
  
  ggplot(aes(swim_group, Abundance, fill = Phylum)) +
  geom_col(position = 'stack') +
  
  theme_classic(base_size = 18) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Swim Performance")

plot_avg

ggsave('../plots/hindgut_plot.jpg',
       plot = plot_avg,
       height=8.5, width = 14)
```

